### ISSUE TITLE
validate current AAI client schema from fed-id to nuvla

### ISSUE THREAD

**Issue by cjdcordeiro** [SixSq/fed-id#2]
The current Client template (SixSq ALL) should map the following user attributes to the final token parameters (keeping the same names):
```
eduPersonScopedAffiliation	
eduPersonTargetedID
uniqueID
schacHomeOrganizationType	
mail	
username	
commonName	
displayName	
eduPersonAffiliation	
schacHomeOrganization
```
 - [ ] verify we can obtain all of these parameters from a token
 - [ ] validate these are all we need
 - [ ] crosscheck their value is consistent when authenticating with different IdPs

**Comment by elegoff** [comment]
tested that we can map additional user attributes and those are present in token

**Comment by cjdcordeiro** [comment]
https://www.dropbox.com/s/gjbui6um2bo43mi/IdPParameterMapping.xlsx?dl=0
